export const uploadTypes = [
  {message: "Selecionar...", value: "select"},
  {message: "Atualização de pedidos", value: "order-update"},
  {message: "Envio de pedidos Amazon", value: "order-amazon-insert"},
  {message: "Envio de pedidos Nuvemshop", value: "order-nuvemshop-insert"},
  {message: "Envio de pedidos Estante Virtual", value: "order-estante-insert"},
  {message: "Envio de pedidos Alibris", value: "order-alibris-insert"},
  {message: "Envio de pedidos FNAC", value: "order-fnac-insert"},
  {message: "Envio de pedidos AbeBooks", value: "order-abebooks-insert"},
  {message: "Ingestão de notas do FSist", value: "fsist-ingestion"},
]

export const fields = {
  "order-update": [
    {label: "Nº", field_name: "id", updatable: false, required: true},
    {label: "Empresa", field_name: "id_company", updatable: false, required: false},
    {label: "Canal de Venda", field_name: "id_sellercentral", updatable: false, required: false},
    {label: "Fase do processo", field_name: "id_phase", updatable: true, required: false},
    {label: "NF", field_name: "invoice_number", updatable: true, required: false},
    {label: "ORIGEM", field_name: "online_order_number", updatable: false, required: true},
    {label: "Nº Bling", field_name: "bling_number", updatable: true, required: false},
    {label: "Data do pedido", field_name: "order_date", updatable: false, required: false},
    {label: "Data prevista", field_name: "expected_date", updatable: false, required: false},
    {label: "ISBN", field_name: "isbn", updatable: false, required: false},
    {label: "Valor", field_name: "selling_price", updatable: false, required: false},
    {label: "Fornecedor", field_name: "supplier_name", updatable: true, required: false},
    {label: "Data da compra", field_name: "purchase_date", updatable: true, required: false},
    {label: "Endereço de entrega", field_name: "id_delivery_address", updatable: true, required: false},
    {label: "Nº Compra fornecedor", field_name: "supplier_purchase_number", updatable: true, required: false},
    {label: "Forma de envio", field_name: "id_delivery_method", updatable: true, required: false},
    {label: "Código de rastreio", field_name: "tracking_code", updatable: true, required: false},
    {label: "Código de coleta", field_name: "collection_code", updatable: true, required: false},
    {label: "Data de entrega", field_name: "delivered_date", updatable: true, required: false},
    {label: "Pedir avaliação", field_name: "ask_rating", updatable: true, required: false},
    {label: "Endereço verificado", field_name: "address_verified", updatable: true, required: false},
    {label: "Pronto para envio", field_name: "ready_for_ship", updatable: true, required: false},
  ],
  "order-amazon-insert": [
    {label: "ID da Empresa", field_name: "id_company", updatable: true, required: true},
    {label: "sales-channel", field_name: "sellercentral", updatable: true, required: true},
    {label: "order-id", field_name: "online_order_number", updatable: true, required: true},
    {label: "payments-date", field_name: "order_date", updatable: true, required: true},
    {label: "latest-ship-date", field_name: "ship_date", updatable: true, required: true},
    {label: "latest-delivery-date", field_name: "expected_date", updatable: true, required: true},
    {label: "sku", field_name: "sku", updatable: true, required: true},
    {label: "item-price", field_name: "item_price", updatable: true, required: true},
    {label: "item-tax", field_name: "item_tax", updatable: true, required: true},
    {label: "shipping-price", field_name: "freight_price", updatable: true, required: true},
    {label: "shipping-tax", field_name: "freight_tax", updatable: true, required: true},
    {label: "item-promotion-discount", field_name: "discount_item", updatable: true, required: true},
    {label: "ship-county", field_name: "county", updatable: true, required: true},
    {label: "cpf", field_name: "cpf_cnpj", updatable: true, required: true},
    {label: "buyer-phone-number", field_name: "buyer_phone", updatable: true, required: true},
    {label: "ship-phone-number", field_name: "ship_phone", updatable: true, required: true},
    {label: "buyer-name", field_name: "buyer_name", updatable: true, required: true},
    {label: "buyer-email", field_name: "buyer_email", updatable: true, required: true},
    {label: "recipient-name", field_name: "recipient_name", updatable: true, required: true},
    {label: "ship-address-1", field_name: "address_1", updatable: true, required: true},
    {label: "ship-address-2", field_name: "address_2", updatable: true, required: true},
    {label: "ship-address-3", field_name: "address_3", updatable: true, required: true},
    {label: "ship-city", field_name: "city", updatable: true, required: true},
    {label: "ship-state", field_name: "state", updatable: true, required: true},
    {label: "ship-postal-code", field_name: "postal_code", updatable: true, required: true},
    {label: "ship-country", field_name: "country", updatable: true, required: true},
    {label: "delivery-Instructions", field_name: "delivery_instructions", updatable: true, required: true},
    {label: "is-business-order", field_name: "is_business_order", updatable: true, required: true},
  ],
  "order-nuvemshop-insert": [
    {label: "Número do Pedido", field_name: "online_order_number", updatable: true, required: true}, 
    {label: "E-mail", field_name: "buyer_email", updatable: true, required: true}, 
    {label: "Data de pagamento", field_name: "order_date", updatable: true, required: true}, 
    {label: "Data de envio", field_name: "ship_date", updatable: true, required: true}, 
    {label: "Data prevista", field_name: "expected_date", updatable: true, required: true}, 
    {label: "Moeda", field_name: "currency", updatable: true, required: true}, 
    {label: "Valor do Produto", field_name: "price", updatable: true, required: true}, 
    {label: "Desconto", field_name: "discount", updatable: true, required: true}, 
    {label: "Valor do Frete", field_name: "freight", updatable: true, required: true}, 
    {label: "Nome do comprador", field_name: "buyer_name", updatable: true, required: true}, 
    {label: "Telefone", field_name: "buyer_phone", updatable: true, required: true}, 
    {label: "Nome para a entrega", field_name: "recipient_name", updatable: true, required: true},
    {label: "Telefone para a entrega", field_name: "ship_phone", updatable: true, required: true},
    {label: "Endereço", field_name: "address_1", updatable: true, required: true},
    {label: "Número", field_name: "number", updatable: true, required: true}, 
    {label: "Complemento", field_name: "address_2", updatable: true, required: true}, 
    {label: "Bairro", field_name: "county", updatable: true, required: true}, 
    {label: "Cidade", field_name: "city", updatable: true, required: true}, 
    {label: "Código postal", field_name: "postal_code", updatable: true, required: true}, 
    {label: "Estado", field_name: "state", updatable: true, required: true}, 
    {label: "País", field_name: "country", updatable: true, required: true}, 
    {label: "SKU", field_name: "sku", updatable: true, required: true}, 
  ],
  "order-estante-insert": [
    {label: "Data de pagamento", field_name: "order_date", updatable: true, required: true}, 
    {label: "Status", field_name: "order_status", updatable: true, required: true}, 
    {label: "Pedido", field_name: "online_order_number", updatable: true, required: true}, 
    {label: "CódigoEv", field_name: "ev_code", updatable: true, required: true}, 
    {label: "Título", field_name: "title", updatable: true, required: true}, 
    {label: "Autor", field_name: "author", updatable: true, required: true}, 
    {label: "Editora", field_name: "publisher", updatable: true, required: true}, 
    {label: "Descrição", field_name: "description", updatable: true, required: true}, 
    {label: "Estante", field_name: "book_type", updatable: true, required: true}, 
    {label: "ISBN", field_name: "isbn", updatable: true, required: true}, 
    {label: "Comprador", field_name: "buyer_name", updatable: true, required: true}, 
    {label: "E-mail do Comprador", field_name: "buyer_email", updatable: true, required: true}, 
    {label: "CPF/CNPJ", field_name: "cpf_cnpj", updatable: true, required: true}, 
    {label: "Destinatário", field_name: "recipient_name", updatable: true, required: true}, 
    {label: "Endereço", field_name: "full_address", updatable: true, required: true}, 
    {label: "Logradouro", field_name: "address_1", updatable: true, required: true}, 
    {label: "Número", field_name: "address_2", updatable: true, required: true}, 
    {label: "Complemento", field_name: "address_3", updatable: true, required: true}, 
    {label: "Bairro", field_name: "county", updatable: true, required: true}, 
    {label: "Estado", field_name: "state", updatable: true, required: true}, 
    {label: "UF", field_name: "uf", updatable: true, required: true}, 
    {label: "Cidade", field_name: "city", updatable: true, required: true}, 
    {label: "CEP", field_name: "postal_code", updatable: true, required: true}, 
    {label: "Forma de envio", field_name: "delivery_method", updatable: true, required: true}, 
    {label: "Código de rastreio", field_name: "tracking_code", updatable: true, required: true}, 
    {label: "Link de rastreio", field_name: "tracking_link", updatable: true, required: true}, 
    {label: "Valor do frete (R$)", field_name: "freight", updatable: true, required: true}, 
    {label: "Juros (R$)", field_name: "item_tax", updatable: true, required: true}, 
    {label: "Preço do Livro (R$)", field_name: "price", updatable: true, required: true}, 
    {label: "Valor Total (R$)", field_name: "value", updatable: true, required: true}, 
    {label: "Data prevista", field_name: "expected_date", updatable: true, required: true}, 
    {label: "Data para envio", field_name: "ship_date", updatable: true, required: true}, 
    {label: "Método de pagamento", field_name: "payment_method", updatable: true, required: true}, 
  ],
  "order-alibris-insert": [
    {label: "Nº do pedido", field_name: "online_order_number", updatable: true, required: true}, 
    {label: "ISBN-13", field_name: "isbn", updatable: true, required: true}, 
    {label: "Valor", field_name: "price", updatable: true, required: true}, 
    {label: "Data de pagamento", field_name: "order_date", updatable: true, required: true}, 
    {label: "Data prevista", field_name: "expected_date", updatable: true, required: true}, 
    {label: "E-mail do cliente", field_name: "buyer_email", updatable: true, required: true}, 
  ],
  "order-fnac-insert": [
    {label: "encomenda", field_name: "online_order_number", updatable: true, required: true}, 
    {label: "Data de criação", field_name: "order_date", updatable: true, required: true}, 
    {label: "Estado da encomenda", field_name: "status", updatable: true, required: true}, 
    {label: "Preço dos produtos (IVA incluído)", field_name: "price", updatable: true, required: true}, 
    {label: "Portes de Envio (IVA incluído)", field_name: "freight", updatable: true, required: true}, 
    {label: "EAN", field_name: "isbn", updatable: true, required: true}, 
    {label: "Telefone", field_name: "ship_phone", updatable: true, required: true}, 
    {label: "Nome do destinatário", field_name: "recipient_name", updatable: true, required: true}, 
    {label: "Apelido do destinatário", field_name: "recipient_surname", updatable: true, required: true}, 
    {label: "Morada 1 do destinatário", field_name: "address_1", updatable: true, required: true}, 
    {label: "Morada 2 do destinatário", field_name: "address_2", updatable: true, required: true}, 
    {label: "Morada 3 do destinatário", field_name: "address_3", updatable: true, required: true}, 
    {label: "Código posta do destinatário", field_name: "postal_code", updatable: true, required: true}, 
    {label: "Cidade do destinatário", field_name: "city", updatable: true, required: true}, 
    {label: "País do destinário", field_name: "country", updatable: true, required: true}, 
    {label: "Nif client", field_name: "nif", updatable: true, required: true}, 
    {label: "Data de envio", field_name: "ship_date", updatable: true, required: false}, 
    {label: "Data prevista", field_name: "expected_date", updatable: true, required: false}, 
  ],
  "order-abebooks-insert": [
    {label: "SKU", field_name: "sku", updatable: true, required: true}, 
    {label: "Quantidade", field_name: "quantity", updatable: true, required: true}, 
    {label: "Order ID", field_name: "online_order_number", updatable: true, required: true}, 
    {label: "Channel", field_name: "selling_channel", updatable: true, required: true}, 
    {label: "Bookprice", field_name: "price", updatable: true, required: true}, 
    {label: "Shipping Price", field_name: "freight", updatable: true, required: true}, 
    {label: "Total", field_name: "total", updatable: true, required: true}, 
    {label: "Shipping Time", field_name: "shipping_time", updatable: true, required: true}, 
    {label: "Date Ordered", field_name: "order_date", updatable: true, required: true}, 
    {label: "Buyer E-mail", field_name: "buyer_email", updatable: true, required: true}, 
    {label: "Buyer Telephone", field_name: "buyer_phone", updatable: true, required: true}, 
    {label: "Shipping Address", field_name: "address_1", updatable: true, required: true}, 
    {label: "City", field_name: "city", updatable: true, required: true}, 
    {label: "UF", field_name: "uf", updatable: true, required: true}, 
    {label: "Country", field_name: "country", updatable: true, required: true}, 
    {label: "ZIP", field_name: "postal_code", updatable: true, required: true}, 
    {label: "Company", field_name: "buyer_name", updatable: true, required: false}, 
    {label: "Complemento", field_name: "address_2", updatable: true, required: true}, 
  ],
  "fsist-ingestion": [
    {label: "Emissão Data/Hora", field_name: "emitted_at", updatable: true, required: true},
    {label: "Mês/Ano", field_name: "period", updatable: true, required: true},
    {label: "Chave", field_name: "key", updatable: true, required: true},
    {label: "Tipo", field_name: "type", updatable: true, required: true},
    {label: "Status", field_name: "status", updatable: true, required: true},
    {label: "Valor", field_name: "value", updatable: true, required: true},
    {label: "Manifestação", field_name: "manifestation", updatable: true, required: true},
    {label: "Tem XML", field_name: "has_xml", updatable: true, required: true},
    {label: "Origem", field_name: "origin", updatable: true, required: true},
    {label: "CFOPs", field_name: "cfops", updatable: true, required: true},
    {label: "Emitente CNPJ", field_name: "emitter_cnpj", updatable: true, required: true},
    {label: "Emitente", field_name: "emitter_name", updatable: true, required: true},
    {label: "Emitente IE", field_name: "emitter_ie", updatable: true, required: true},
    {label: "Emitente UF", field_name: "emitter_uf", updatable: true, required: true},
    {label: "Destinatário CNPJ/CPF", field_name: "recipient_cnpj", updatable: true, required: true},
    {label: "Destinatário", field_name: "recipient_name", updatable: true, required: true},
    {label: "Destinatário IE", field_name: "recipient_ie", updatable: true, required: true},
    {label: "Destinatário UF", field_name: "recipient_uf", updatable: true, required: true},
    {label: "Transportadora CNPJ/CPF", field_name: "courier_cnpj", updatable: true, required: true},
    {label: "Transportadora", field_name: "courier_name", updatable: true, required: true},
    {label: "Transportadora IE", field_name: "courier_ie", updatable: true, required: true},
    {label: "Transportadora UF", field_name: "courier_uf", updatable: true, required: true},
  ]
} as {[key: string]: {label: string, field_name: string, updatable: boolean, required: boolean}[]}
